"""Parent class for SunsynkNames enum."""

from enum import Enum, unique


@unique
class SunsynkApiNames(str, Enum):
    """Device names used by Sunsynk."""

    PowerView = "PowerView"
    Sunsynk = "Sunsynk"


@unique
class SunsynkNames(str, Enum):
    """Device names used by Sunsynk."""

    SolarProduction = "Solar Production"
    SolarToBattery = "Solar to Battery"
    SolarToGrid = "Solar to Grid"
    SolarToLoad = "Solar to Load"
    TotalLoad = "Total Load"
    GridToLoad = "Grid to Load"
    GridToBattery = "Grid to Battery"
    StateOfCharge = "State of Charge"
    SettingAverageCap = "Setting - Average State of Charge Capacity"
    Charge = "Charge"
    Discharge = "Discharge"
    EVCharger = "EV Charger"
    GridIOL1 = "Instantaneous Grid I/O L1"
    GridIOL2 = "Instantaneous Grid I/O L2"
    GridIOL3 = "Instantaneous Grid I/O L3"
    Generation = "Instantaneous Generation"
    BatterySOC = "Instantaneous Battery SOC"
    BatteryIO = "Instantaneous Battery I/O"
    GridIOTotal = "Instantaneous Grid I/O Total"
    GridPowerTotal = "Instantaneous Grid Power Total"
    Load = "Instantaneous Load"
    PPV1 = "Instantaneous PPV1"
    PPV2 = "Instantaneous PPV2"
    PPV3 = "Instantaneous PPV3"
    PPV4 = "Instantaneous PPV4"
    IPV1 = "Instantaneous IPV1"
    IPV2 = "Instantaneous IPV2"
    IPV3 = "Instantaneous IPV3"
    IPV4 = "Instantaneous IPV4"
    VPV1 = "Instantaneous VPV1"
    VPV2 = "Instantaneous VPV2"
    VPV3 = "Instantaneous VPV3"
    VPV4 = "Instantaneous VPV4"
    PVCurrent = "PV Total Current"
    PVEtotal = "PV Total Energy"
    # Load
    LoadTotalUsed = "Load Total Used"
    LoadVolt = "Load Voltage"
    LoadUpsPower = "Load UPS Power"
    LoadFac = "Load Frequency"
    LoadCurrent = "Load Current"
    # Battery
    BatteryTemp = "Battery Temperature"
    BatteryVoltage = "Battery Voltage"
    BatteryChargeVolt = "Battery Charge Voltage"
    BatteryStatus = "Battery Status"
    BatteryChargeCurrentLimit = "Battery Charge Current Limit"
    BatteryDischargeCurrentLimit = "Battery Discharge Current Limit"
    BatteryCapacity = "Battery Capacity"
    BatteryCurrent = "Battery Current"
    BatteryEtotalChg = "Battery Total Charged"
    BatteryEtotalDischg = "Battery Total Discharged"
    BatteryEfficiency = "Battery Efficiency"
    # Grid
    GridTotalIn = "Grid Total Import"
    GridTotalOut = "Grid Total Export"
    GridFac = "Grid Frequency"
    GridStatus = "Grid Status"
    GridPF = "Grid Power Factor"
    GridVolt = "Grid Voltage"
    GridCurrent = "Grid Current"
    # Output
    OutputPowerAux = "Output Aux Power"
    OutputEtotal = "Output Total Energy"
    OutputEtoday = "Output Today Energy"
    OutputPAC = "Output Power"
    OutputPInv = "Output Inverter Power"
    OutputFac = "Output Frequency"
    OutputVolt = "Output Voltage"
    OutputCurrent = "Output Current"
    # Energy Flow
    FlowBatterySOC = "Flow Battery SOC"
    FlowLoadPower = "Flow Load Power"
    FlowPVPower = "Flow PV Power"
    FlowBatteryPower = "Flow Battery Power"
    FlowGridPower = "Flow Grid Power"
    FlowGenPower = "Flow Generator Power"
    FlowMinPower = "Flow Min Power"
    FlowHeatPumpPower = "Flow Heat Pump Power"
    FlowSmartLoadPower = "Flow Smart Load Power"
    FlowHomeLoadPower = "Flow Home Load Power"
    # Inverter Status
    InverterStatus = "Inverter Status"
    GatewayStatus = "Gateway Status"
    # Cap settings (SOC % per time slot)
    Cap1 = "Setting Cap 1"
    Cap2 = "Setting Cap 2"
    Cap3 = "Setting Cap 3"
    Cap4 = "Setting Cap 4"
    Cap5 = "Setting Cap 5"
    Cap6 = "Setting Cap 6"
    # Energy mode
    EnergyMode = "Setting Energy Mode"
    # Sell times
    SellTime1 = "Setting Sell Time 1"
    SellTime2 = "Setting Sell Time 2"
    SellTime3 = "Setting Sell Time 3"
    SellTime4 = "Setting Sell Time 4"
    SellTime5 = "Setting Sell Time 5"
    SellTime6 = "Setting Sell Time 6"
    # Time on/off
    Time1on = "Setting Time 1 On"
    Time2on = "Setting Time 2 On"
    Time3on = "Setting Time 3 On"
    Time4on = "Setting Time 4 On"
    Time5on = "Setting Time 5 On"
    Time6on = "Setting Time 6 On"
    # Generator time on/off
    GenTime1on = "Setting Gen Time 1 On"
    GenTime2on = "Setting Gen Time 2 On"
    GenTime3on = "Setting Gen Time 3 On"
    GenTime4on = "Setting Gen Time 4 On"
    GenTime5on = "Setting Gen Time 5 On"
    GenTime6on = "Setting Gen Time 6 On"
    # Sell time PAC
    SellTime1Pac = "Setting Sell Time 1 PAC"
    SellTime2Pac = "Setting Sell Time 2 PAC"
    SellTime3Pac = "Setting Sell Time 3 PAC"
    SellTime4Pac = "Setting Sell Time 4 PAC"
    SellTime5Pac = "Setting Sell Time 5 PAC"
    SellTime6Pac = "Setting Sell Time 6 PAC"
